service: nondenbot-reply

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  environment:
    LINE_CHANNE_TOKEN: LINE_CHANNE_TOKEN  
    LINE_CHANNEL_SECRET: LINE_CHANNEL_SECRET
    LINE_ACCESS_TOKEN: LINE_ACCESS_TOKEN

custom:
  defaultStage: stage


package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  bot:
    handler: bin/bot
    events:
      - httpApi:
          path: /reply-bot
          method: POST